name: CI

on:
  workflow_dispatch:
  
env: 
  S3_BUCKET_NAME: send-quiz-deploy
  PROJECT_NAME: send-quiz

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x backend/gradlew
        shell: bash
        
      - name: use secret application-dev.yml - test
        env:
          DEV_APP_CONFIG: ${{ secrets.DEV_APP_CONFIG }}
          OCCUPY_SECRET_DIR: backend/src/test/resources
          OCCUPY_SECRET_DIR_FILE_NAME: application-dev.yml
        run: echo $DEV_APP_CONFIG | base64 -d > $OCCUPY_SECRET_DIR/$OCCUPY_SECRET_DIR_FILE_NAME

      - name: Test
        run: ./gradlew test
        working-directory: backend

      - name: use secret application-prod.yml - main
        env:
          PROD_APP_CONFIG: ${{ secrets.PROD_APP_CONFIG }}
          OCCUPY_SECRET_DIR: backend/src/main/resources
          OCCUPY_SECRET_DIR_FILE_NAME: application-prod.yml
        run: echo $PROD_APP_CONFIG | base64 -d > $OCCUPY_SECRET_DIR/$OCCUPY_SECRET_DIR_FILE_NAME

      - name: Build
        run: ./gradlew build -x test
        working-directory: backend

      - name: Make zip file
        run: zip -r ./$GITHUB_SHA.zip .
        shell: bash
        working-directory: backend

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$S3_BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip
        working-directory: backend
